### ISSUE TITLE
Did !swap but was still killed by reaper

### ISSUE THREAD

**Issue by jacob1** [lykoss/lykos#442] opened 2020-06-07 00:14 UTC
During a game today, my connection crashed again. I immediately did !swap from my alternate connection, but found myself unable to vote. I didn't attempt any other channel or PM commands during this time. Eventually I was removed from the game by the reaper.

The connection I did the !swap on had been in the channel for a long period of time. It was identified to the same account, with the same hostmask, only difference is that the ident was jacob1 vs. ~jacob1.

Notes from moonmoon:
Sat 06-06 [20:04:21] <moonmoon> basically your new connection was somehow in users._ghosts
Sat 06-06 [20:04:29] <moonmoon> and people in that set are completely ignored by lykos
Sat 06-06 [20:04:44] <moonmoon> so somehow your join or swap didn't remove you from it

Here's some logs, may be mildly helpful:

Sat 06-06 [19:39:13] * jacob1 (jacob1@Powder/Developer/lykos.jacob1) has quit (Remote host closed the connection)
Sat 06-06 [19:39:13] <lykos> jacob1 has gone missing.

In pm:
Sat 06-06 [19:39:20] <mooo> swap
Sat 06-06 [19:39:21] <lykos> You are a succubus.

Back in channel:
Sat 06-06 [19:39:20] * lykos gives voice to mooo
Sat 06-06 [19:39:21] <lykos> mooo has swapped places with jacob1.

Unable to vote. 60 seconds after the original crash, an idle out happens:
Sat 06-06 [19:40:18] <lykos> mooo was mauled by wild animals and has died. It seems that succubus meat is tasty.

**Comment by nyuszika7h** [comment] 2020-06-07 00:18
Duplicate of #438

**Closed** 2020-06-07 00:19 UTC
Labels: duplicate
