### ISSUE TITLE
Show number of votes necessary for lynching

### ISSUE THREAD

**Issue by Sanqui** [lykoss/lykos#243] opened 2016-08-24 08:51 UTC
I propose changing the following message:

```
<@lykos> Sanqui votes for lykos.
```

to include the number of votes left for lynching:

```
<@lykos> Sanqui votes for lykos. (1 more vote necessary for lynching)
<@lykos> Sanqui votes for lykos. (1/2)
```

First variant is more verbose, second is more informative, both are fine by me.

**Comment by skizzerz** [comment] 2016-08-25 00:12
I'm not opposed to this, but do note that there are some corner cases that need to be taken into consideration, which could cause that message to display very unusual results.

1. Easiest corner case is "what do you do when that is the vote that causes a successful lynch"? In my opinion, we simply would not display that message in this scenario
2. We have three totems that directly impact voting: impatience, pacifism, and influence. All three of these are hidden totems, meaning the person with that totem can !vote and lykos pretends that everything worked out just fine even if behind-the-scenes their vote was counted twice or not counted at all. If we do this, we'll get messages like "0 more votes necessary to lynch", or possibly even a negative number if multiple people are impacted by such totems. If a person with influence totem votes, it will show (for example) "2 more votes necessary to lynch", and then the next person to vote will trigger the lynch even though it "should" still need 1 more vote.

As such, the message will be as accurate as the !votes list, in the sense that lykos will just sometimes outright lie to you about how many votes are needed to lynch someone. We can expose these counts to make them more visible, but it will have some funny results sometimes by design.

**Comment by kernelpanic3** [comment] 2016-08-25 16:38
Agree with Asorailahd on the second variant. As for the corner cases...

1. IMO it should display as (2/2) or something along those lines, for the sake of clarity and consistency.
2. The message really doesn't need to be any more accurate than the !votes list anyway - as I understand it the intention here is to reduce the necessity of using that list to check.

**Comment by MJ94** [comment] 2016-08-25 16:44
Honestly, I'm not a fan of this. I feel as if this may encourage bandwagons and I don't see any issue with the way we currently show the required votes; in fact, I prefer the way we currently display required votes. I know that this request wouldn't be a replacement for what we currently do, but I still am not a big fan of the idea.

**Comment by Sanqui** [comment] 2016-08-25 19:54
@MJ94: The same way it can encourage bandwagons, it can discourage them.  If I **know** the vote I cast would result in the lynch, I will be much more careful in placing it!  But if I'm too lazy to check (nobody likes !votes spam) or miscount, I'm not going to expect it.

**Comment by skizzerz** [comment] 2019-03-05 19:04
Closing, this is not currently possible to achieve in any meaningful way given how game modes and roles can interact with voting. We actually do not know how many votes on a given player are required to successfully lynch them at the time a !vote is made.

**Closed by skizzerz** 2019-03-05 19:04 UTC
Labels: discussion, enhancement
