### ISSUE TITLE
User quit, lynched, joined to deadchat

### ISSUE THREAD

**Issue by MJ94** [lykoss/lykos#215] opened 2016-01-30 03:57 UTC
Stareh pinged out while in game, she was lynched to prevent stasis, and lykos stated that Stareh joined deadchat. This isn't true, however, because she was not on the network at the time of the lynching.

**Comment by skizzerz** [comment] 2016-01-30 04:06
Technically she *did* join (in the sense that if she reconnected she'd automatically be in deadchat). Yay pedantry! :P

**Comment by jacob1** [comment] 2016-01-30 04:07
Well technically, anyone could have done /nick Stareh and been in deadchat, even if they were unidentified, in stasis, or an alt of someone in game

**Comment by nyuszika7h** [comment] 2016-06-23 19:47
The original reported issue is not so serious, but what @jacob1 says is worrying.

**Comment by skizzerz** [comment] 2016-06-23 20:10
The issue @jacob1 mentioned is tracked as #217. Closing as duplicate

**Closed by skizzerz** 2016-06-23 20:10 UTC
Labels: bug, gameplay

**Comment by nyuszika7h** [comment] 2017-07-20 16:25
Duplicate of #217.

(This is just for tracking purposes, there is nothing that needs to be done with this issue. See [here](https://github.com/blog/2398-manage-issues-and-pull-requests-with-keyword-updates).)
