### ISSUE TITLE
dullahan's death effect killed someone not on the hitlist

### ISSUE THREAD

**Issue by ishanyx** [lykoss/lykos#391] opened 2019-09-28 02:57 UTC
I was dullahan in sleepy with the following target list at the beginning of the game:
`22:38:20 <lykos> Remaining targets: spookly, aismallard, fool`
I killed fool, then died the next night at the same time I killed spookly. I would expect the spine whip to try to hit the only remaining entry on the list, aismallard (and fail due to priest's blessed villager status) but instead it hit a random other player:
`22:46:49 <@lykos> The dead body of misha, a dullahan, is found. Those remaining mourn the tragedy.`
`22:46:49 <@lykos> The dead body of spookly, a villager, is found. Those remaining mourn the tragedy.`
`22:46:49 <@lykos> Before dying, misha snaps a whip made of a human spine at WFeather, killing them. The village mourns the loss of a wolf.`

**Comment by skizzerz** [comment] 2019-11-15 17:39
Caused by the list being wrong, not the death effect itself. There should've been 4 targets (including the one that died).

Message refactor likely fixed this so marking as closed.

**Closed by skizzerz** 2019-11-15 17:39 UTC
Labels: bug, gameplay
