### ISSUE TITLE
Feature request: conditional join

### ISSUE THREAD

**Issue by Michagogo** [lykoss/lykos#127] opened 2015-04-28 18:34 UTC
An option to say "join me to a <x>-player game" would be nice, because it would allow including them in the total (for example, if 3 people say "!joinif 8", then at 5p you can join the three of them together and you've just reached 8 players. This would need to expire, though, after... idk, 5 minutes? 1? 3? Not sure.

**Comment by rika314** [comment] 2015-04-28 18:34
#43

**Comment by Michagogo** [comment] 2015-04-28 18:41
Actually, I don't think it needs its own timeout. I feel like the current 1-hour timeout for a game to start is ridiculous, and I can see a lot of people idling in the space of that hour, but I don't think a conditional join actually needs any more restrictive timeout.

**Comment by nyuszika7h** [comment] 2015-04-28 18:47
Feature request rejected. There is `!pingif`. We won't be adding another way to increase the number of idlers.

**Closed by nyuszika7h** 2015-04-28 18:47 UTC
Labels: duplicate, wontfix

**Comment by nyuszika7h** [comment] 2017-07-20 16:25
Duplicate of #43.

(This is just for tracking purposes, there is nothing that needs to be done with this issue. See [here](https://github.com/blog/2398-manage-issues-and-pull-requests-with-keyword-updates).)
